spring.application.name=ms-clientes
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/bd_clientes
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration